name: Update Trivy Cache

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-trivy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Restore Trivy DB Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: cache-trivy-${{ runner.os }}-${{ github.default_branch }}
          restore-keys: |
            cache-trivy-${{ runner.os }}-

      - name: Setup oras
        uses: oras-project/setup-oras@v1

      - name: Create Trivy cache directories
        run: |
          mkdir -p ~/.cache/trivy/db
          mkdir -p ~/.cache/trivy/java-db

      - name: Download and extract the vulnerability DB
        run: |
          oras pull ghcr.io/aquasecurity/trivy-db:2
          tar -xzf db.tar.gz -C ~/.cache/trivy/db
          rm db.tar.gz

      - name: Download and extract the Java DB
        run: |
          oras pull ghcr.io/aquasecurity/trivy-java-db:1
          tar -xzf javadb.tar.gz -C ~/.cache/trivy/java-db
          rm javadb.tar.gz

      - name: Cache DBs
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: cache-trivy-${{ runner.os }}-${{ github.default_branch }}
